apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gaqz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gaqz
    app.kubernetes.io/part-of: byoc-app-vkec
  name: gaqz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: gaqz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: gaqz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-olwe-tenant/byoc-app-vkec/gaqz@sha256:f7d97b57ec0d691496e8e96cc9f5b33c46660a0ad0f599e89f47be19a23c29dd
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
