apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gaqz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gaqz
    app.kubernetes.io/part-of: byoc-app-vkec
  name: gaqz
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: gaqz
status:
  loadBalancer: {}
