apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gaqz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gaqz
    app.kubernetes.io/part-of: byoc-app-vkec
  name: gaqzddd1
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: gaqz
    weight: null
status: {}
